mqtt:
  enabled: true
  host: 10.118.50.57
  port: 1883
  user: camera_client
  password: S347367j

tls:
  enabled: false

cameras:
  name_of_your_camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:petabyte2024@10.118.210.122:554/ # <----- The stream you want to use for detection
          roles:
            - detect
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
    objects:
      track:
        - car # <---- Add car to the list of objects to track globally
      filters:
        car: {}
    zones:
      test:
        coordinates: 0.172,0.24,0.172,0.524,0.482,0.518,0.488,0.235
        loitering_time: 0
        objects:
          - car # <---- Ensure objects is defined as a list here
        inertia: 3
    review:
      alerts:
        required_zones: test

record:
  enabled: true
  retain:
    days: 0
    mode: all
  events:
    retain:
      default: 30
      mode: motion

version: 0.14
